import type { Task } from "@cognix/types";

export const mockTasks: Task[] = [
  {
    id: "task_1",
    projectId: "proj_demo",
    parentTaskId: null,
    title: "Design Task Management Dashboard",
    description:
      "Create high-fidelity mockups for the task management dashboard with a premium look and feel.",
    status: "in_progress",
    priority: "high",
    type: "task",
    assigneeId: "user_1",
    reporterId: "user_2",
    assignedAgentId: null,
    dueDate: new Date(Date.now() + 86400000 * 3).toISOString(), // +3 days
    startDate: new Date().toISOString(),
    completedAt: null,
    estimatedHours: 8,
    actualHours: null,
    position: 0,
    metadata: {},
    aiContext: {},
    aiStatus: "idle",
    isRecurring: false,
    recurrenceRule: null,
    nextOccurrence: null,
    createdAt: new Date(Date.now() - 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
    labels: [
      {
        id: "l_1",
        projectId: "proj_demo",
        name: "Design",
        color: "blue",
        createdAt: "",
        updatedAt: "",
      },
    ],
  },
  {
    id: "task_2",
    projectId: "proj_demo",
    parentTaskId: null,
    title: "Implement Kanban Board using dnd-kit",
    description: "Set up dnd-kit for drag and drop functionality on the Kanban board.",
    status: "todo",
    priority: "urgent",
    type: "feature",
    assigneeId: "user_1",
    reporterId: "user_2",
    assignedAgentId: null,
    dueDate: new Date(Date.now() + 86400000 * 2).toISOString(),
    startDate: null,
    completedAt: null,
    estimatedHours: 12,
    actualHours: null,
    position: 1,
    metadata: {},
    aiContext: {},
    aiStatus: "idle",
    isRecurring: false,
    recurrenceRule: null,
    nextOccurrence: null,
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    updatedAt: new Date().toISOString(),
    labels: [
      {
        id: "l_2",
        projectId: "proj_demo",
        name: "Frontend",
        color: "green",
        createdAt: "",
        updatedAt: "",
      },
    ],
  },
  {
    id: "task_3",
    projectId: "proj_demo",
    parentTaskId: null,
    title: "Fix issue with Ruff linting in backend",
    description:
      "Ensure Ruff is running properly with maximum warnings 0 in the lint-staged pipeline.",
    status: "done",
    priority: "medium",
    type: "bug",
    assigneeId: null,
    reporterId: "user_1",
    assignedAgentId: null,
    dueDate: null,
    startDate: null,
    completedAt: new Date().toISOString(),
    estimatedHours: 2,
    actualHours: 1.5,
    position: 0,
    metadata: {},
    aiContext: {},
    aiStatus: "idle",
    isRecurring: false,
    recurrenceRule: null,
    nextOccurrence: null,
    createdAt: new Date(Date.now() - 86400000 * 5).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    labels: [],
  },
  {
    id: "task_4",
    projectId: "proj_demo",
    parentTaskId: null,
    title: "Write SQLAlchemy models for Task Engine",
    description:
      "Translate Prisma schema to SQLAlchemy models for Tasks, TaskActivity, and Labels.",
    status: "in_review",
    priority: "high",
    type: "feature",
    assigneeId: "user_1",
    reporterId: "user_1",
    assignedAgentId: null,
    dueDate: null,
    startDate: null,
    completedAt: null,
    estimatedHours: 6,
    actualHours: 5,
    position: 0,
    metadata: {},
    aiContext: {},
    aiStatus: "idle",
    isRecurring: false,
    recurrenceRule: null,
    nextOccurrence: null,
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    updatedAt: new Date().toISOString(),
    labels: [
      {
        id: "l_3",
        projectId: "proj_demo",
        name: "Backend",
        color: "purple",
        createdAt: "",
        updatedAt: "",
      },
    ],
  },
];
